apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: {{.Release.Namespace}}
data:
  grafana.ini: |
{{ if .Values.enableHttps }}
    {{ range .Files.Lines "config/grafana.ini" }}
    {{ . }}{{ end }}
{{ else }}
    {{ range .Files.Lines "config/grafana-http.ini" }}
    {{ . }}{{ end }}
{{ end }}