apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-cluster-config
  namespace: {{.Release.Namespace}}
data:
  "configs": |
    {{ range .Files.Lines "conf/redis-cluster-config.yaml" }}
    {{ . }}{{ end }}