apiVersion: v1
kind: Service
metadata:
  name: squids-cloud-site-headless
  namespace: squids
  labels:
    app-name: squids-cloud-site
spec:
  ports:
    - port: {{ .Values.service.http.port }}
      targetPort: {{ .Values.service.http.port }}
      protocol: TCP
      name: http
    {{ if eq .Values.env "pro" }}
    - port: {{ .Values.service.https.port }}
      targetPort: {{ .Values.service.https.port }}
      protocol: TCP
      name: https
    {{ end }}
  selector:
    app-name: squids-cloud-site
