apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager
  namespace: {{.Release.Namespace}}
  labels:
    app.kubernetes.io/instance: alertmanager
    app.kubernetes.io/name: alertmanager
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
      smtp_from: "notification@squids.io"
      smtp_smarthost: smtp.exmail.qq.com:465
      smtp_hello: "qq.com"
      smtp_auth_username: notification@squids.io
      smtp_auth_password: vnDAQ9VVWTEo9aCN
      smtp_require_tls: false
    receivers:
    - name: squids
      email_configs:
      - to: "notification@squids.io"
        send_resolved: false
    route:
      group_interval: 5m
      group_wait: 10s
      receiver: squids
      repeat_interval: 1h
    templates:
    - /etc/alertmanager/*.tmpl