apiVersion: v1
kind: Service
metadata:
  name: mysql-operator
  labels:
    app.kubernetes.io/name: mysql-operator
    vendor: grdscloud
spec:
  selector:
    app.kubernetes.io/name: mysql-operator
    vendor: grdscloud
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: apiserver
      protocol: TCP
      port: 8443
      targetPort: 8443
    - name: metrics
      port: 8080
